interface Province {
    value: string; // ใช้ตัวย่อภาษาอังกฤษเป็น value
    label: string; // ใช้ชื่อจังหวัดเป็น label
  }
  
  const provinces: Province[] = [
    { value: "BKK", label: "กรุงเทพมหานคร" },
    { value: "KBI", label: "กระบี่" },
    { value: "KAN", label: "กาญจนบุรี" },
    { value: "KAL", label: "กาฬสินธุ์" },
    { value: "KPT", label: "กำแพงเพชร" },
    { value: "KKC", label: "ขอนแก่น" },
    { value: "CTI", label: "จันทบุรี" },
    { value: "CCO", label: "ฉะเชิงเทรา" },
    { value: "CBI", label: "ชลบุรี" },
    { value: "CNT", label: "ชัยนาท" },
    { value: "CPM", label: "ชัยภูมิ" },
    { value: "CPN", label: "ชุมพร" },
    { value: "CRI", label: "เชียงราย" },
    { value: "CMI", label: "เชียงใหม่" },
    { value: "TRG", label: "ตรัง" },
    { value: "TRT", label: "ตราด" },
    { value: "TAK", label: "ตาก" },
    { value: "NYK", label: "นครนายก" },
    { value: "NPT", label: "นครปฐม" },
    { value: "NPM", label: "นครพนม" },
    { value: "NMA", label: "นครราชสีมา" },
    { value: "NST", label: "นครศรีธรรมราช" },
    { value: "NSW", label: "นครสวรรค์" },
    { value: "NBI", label: "นนทบุรี" },
    { value: "NWT", label: "นราธิวาส" },
    { value: "NAN", label: "น่าน" },
    { value: "BKN", label: "บึงกาฬ" },
    { value: "BRM", label: "บุรีรัมย์" },
    { value: "PTN", label: "ปทุมธานี" },
    { value: "PKN", label: "ประจวบคีรีขันธ์" },
    { value: "PRI", label: "ปราจีนบุรี" },
    { value: "PTT", label: "ปัตตานี" },
    { value: "AYA", label: "พระนครศรีอยุธยา" },
    { value: "PYO", label: "พะเยา" },
    { value: "PNA", label: "พังงา" },
    { value: "PLG", label: "พัทลุง" },
    { value: "PCT", label: "พิจิตร" },
    { value: "PLK", label: "พิษณุโลก" },
    { value: "PBI", label: "เพชรบุรี" },
    { value: "PCB", label: "เพชรบูรณ์" },
    { value: "PRE", label: "แพร่" },
    { value: "PKT", label: "ภูเก็ต" },
    { value: "MKM", label: "มหาสารคาม" },
    { value: "MDH", label: "มุกดาหาร" },
    { value: "MSN", label: "แม่ฮ่องสอน" },
    { value: "YST", label: "ยโสธร" },
    { value: "YLA", label: "ยะลา" },
    { value: "ROI", label: "ร้อยเอ็ด" },
    { value: "RNG", label: "ระนอง" },
    { value: "RYG", label: "ระยอง" },
    { value: "RBR", label: "ราชบุรี" },
    { value: "LRI", label: "ลพบุรี" },
    { value: "LPG", label: "ลำปาง" },
    { value: "LPN", label: "ลำพูน" },
    { value: "LEI", label: "เลย" },
    { value: "SIS", label: "ศรีสะเกษ" },
    { value: "SNK", label: "สกลนคร" },
    { value: "SKA", label: "สงขลา" },
    { value: "STU", label: "สตูล" },
    { value: "SPK", label: "สมุทรปราการ" },
    { value: "SKM", label: "สมุทรสงคราม" },
    { value: "SKN", label: "สมุทรสาคร" },
    { value: "SKW", label: "สระแก้ว" },
    { value: "SRI", label: "สระบุรี" },
    { value: "SGB", label: "สิงห์บุรี" },
    { value: "STI", label: "สุโขทัย" },
    { value: "SPB", label: "สุพรรณบุรี" },
    { value: "SNI", label: "สุราษฎร์ธานี" },
    { value: "SUR", label: "สุรินทร์" },
    { value: "NKI", label: "หนองคาย" },
    { value: "NLH", label: "หนองบัวลำภู" },
    { value: "ATG", label: "อ่างทอง" },
    { value: "ACR", label: "อำนาจเจริญ" },
    { value: "UDN", label: "อุดรธานี" },
    { value: "UTT", label: "อุตรดิตถ์" },
    { value: "UTH", label: "อุทัยธานี" },
    { value: "UBN", label: "อุบลราชธานี" },
  ];
  
  export default provinces;