import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "../app/component/navbar"
import SearchableBox from "./component/SearchableBox"
import SearchableFilter from "./component/SearchableFilter";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const options = [
    { value: 'account-settings', label: 'Account settings' },
    { value: 'support', label: 'Support' },
    { value: 'license', label: 'License' },
    { value: 'sign-out', label: 'Sign out' },
    { value: 'profile', label: 'Profile' },
    { value: 'settings', label: 'Settings' },
  ];

  return (
    <html lang="en" >  
      <body >
      <div className="grid grid-rows-[auto_1fr_auto] grid-cols-[300px_1fr] min-h-screen ">
      <header className="col-span-2 border border-b-gray-200">
        <Nav />
      </header>
      <aside className="col-span-1 bg-gray-100 row-start-2 border border-r-gray-200">
      <SearchableBox />
      <SearchableFilter />
      </aside>
      <main  className="col-span-1 row-start-2">
        {children}
      </main>
      <footer className="col-span-2 row-start-3 bg-gray-300 p-5 border-t-gray-200">
        Footer
      </footer>
    </div>
      </body>
    </html>
  );
}
